n1 = int (input('digite um numero:'))
n2 = int (input('digite outro numero:'))
soma = (n1+n2)
#print('o resultado da soma entre',(n1),'e',(n2),'é:', soma)
print("o resultado da soma entre {} e {} é: {}".format(n1,n2,soma))
