a = input("digite algo: ")
print("Qual o tipo primitivo desse valor?:", type(a))
print("Ele só tem espaços?", a.isspace())
print("Ele é um numero?", a.isnumeric())
print("Ele é alfabetico?", a.isalpha())
print("Ele é alfanúmerico?", a.isalnum())
print("Ele está em maiúscula?", a.isupper())
print("Ele está em minusculas?", a.islower())
print("Ele está captalizada?", a.istitle())
